[package]
name = "Supratokentelegram"
version = "1.0.0"
authors = []

[addresses]
0xcafe = "0x1c5acf62be507c27a7788a661b546224d806246765ff2695efece60194c6df05"
//add your address for the Module deployment as this is already deployed on my address above.

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]
